name: Forms
version: "1.2.14"
license: "GPL-2.0-or-later"
date: 2026-01-26
description: |
    Sesquilinear and Quadratic

authors:
    - name: John Bamberg
      url: https://johnbamberg.github.io
    - name: Jan De Beule
      url: http://www.debeule.eu

maintainers:
    - name: John Bamberg
      url: https://johnbamberg.github.io
    - name: Jan De Beule
      url: http://www.debeule.eu
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.9"

www: https://gap-packages.github.io/forms
readme: README
packageinfo: https://gap-packages.github.io/forms/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/forms/releases/download/v1.2.14/forms-1.2.14.tar.gz
    - name: .zip
      url: https://github.com/gap-packages/forms/releases/download/v1.2.14/forms-1.2.14.zip
    - name: .tar.bz2
      url: https://github.com/gap-packages/forms/releases/download/v1.2.14/forms-1.2.14.tar.bz2

abstract: |
    This package can be used for work with sesquilinear and quadratic forms on finite vector spaces; objects that are used to describe polar spaces and classical groups.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Forms, Sesquilinear, Quadratic.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BBH26</span>]   <b class='BibAuthor'>Bamberg, J., De Beule, J. and Horn, M.</b>,
     <i class='BibTitle'>Forms, Sesquilinear and Quadratic,
             Version 1.2.14</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/forms">https://gap-packages.github.io/forms</a></span>.
    </p>
    

bibtex: |
    @misc{ Forms,
      author =           {Bamberg, J. and De Beule, J. and Horn, M.},
      title =            {{Forms},   {Sesquilinear   and  Quadratic},  {V}ersion
                          1.2.14},
      month =            {Jan},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/forms}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{forms}}},
      keywords =         {Forms; Sesquilinear; Quadratic},
      printedkey =       {BBH26}
    }

